### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by tenJirka** [hexdump0815/linux-mainline-tegra-k1-kernel#2]
I tried your kernel and it's working so nicely. Excellent job.
I know it's probably because of nouveau don't work with it yet, but is there any other option how to get sound to work?
I'm using this kernel with ubuntu 20 and kubuntu desktop, beacause of better graphic perfomance, but sound is missing.

**Comment by hexdump0815** [comment]
it should actually work, you just have to enable left dac left speaker and right dac right speaker channels (or same for headphone channels) in the mixer via amixer tool (be prepared that it has a lot of channels) to make it work - i plan to create a proper also ucm file to make this automatic when i have time ... good luck!

**Comment by tenJirka** [comment]
You are right. I enabled it in alsamixer (i'm not so familiar with amixer) and it worked. 
I tried something similar before, but I didn't know, a have to enable dac to. 
Thanks.
